### ISSUE TITLE
How can i install with https ssl?

### ISSUE THREAD

**Issue by rodrigocaugusto** [ONLYOFFICE/snap-documentserver#120]
Hello i need install a ssl on snap-document server

**Comment by igwyd** [comment]
Hello @rodrigocaugusto, you can use our guid https://github.com/ONLYOFFICE/snap-documentserver#installation-of-the-ssl-certificates

**Comment by edsonsbj** [comment]
You can generate a certificate with Let's encrypt and then convert fullchaim.pem to cert.crt and privkey.pem to privkey.key with the commands below
`openssl x509 -outform der -in fullchaim.pem -out onlyoffice.crt`
`openssl pkey -in privkey1.pem -out onlyoffice.key`

If it doesn't work at first, try converting the cert.pem file instead of fullchaim.pem

**Comment by igwyd** [comment]
@edsonsbj .pem, .crt and .key only name, no need use openssl conversation for change pem to crt, you can just rename it. For example create certs with LE, after rename it ```mv fullchaim.pem onlyoffice.crt``` ```mv privkey.pem onlyoffice.key``` and copy them to ```/var/snap/onlyoffice-ds/current/var/www/onlyoffice/Data/certs/```

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
